### ISSUE TITLE
[React2Hooks] Default exports

### ISSUE THREAD

**Issue by morgante** [getgrit/js#162]
As seen in [this PR](https://github.com/Superset-Community-Partners/superset/pull/9/files), the pattern does a poor job when a class component is exported as the default for a package:

```
export default class Expandable extends React.Component<Props, State> {
  ...
}
```

**Comment by seren5240** [comment]
We're still having problems with "export default": https://app.grit.io/studio?key=1eOYUx4hwMiNEMsw9UWQM

**Comment by morgante** [comment]
I think it's because that's not a node by itself. This works:

```
$x where $x <: r"export default const.+"
```
