### ISSUE TITLE
openai v4 might be missing a codemod

### ISSUE THREAD

**Issue by yisding** [getgrit/js#169]
Tried to run it on one of my old repos: https://github.com/yisding/readpanda

Looks like it needs to replace OpenAIApi with OpenAI.

diff --git a/pages/api/image.ts b/pages/api/image.ts
index e2f4f87..1206cda 100644
--- a/pages/api/image.ts
+++ b/pages/api/image.ts
@@ -1,5 +1,5 @@
 import type { NextApiRequest, NextApiResponse } from "next";
-import { Configuration, OpenAIApi } from "openai";
+import OpenAI from "openai";

 const openai = new OpenAIApi(
   new Configuration({
@@ -23,7 +23,7 @@ export default async function handler(

   const { word } = req.query;

-  const response = await openai.createImage({
+  const response = await openai.images.generate({
     prompt: `clip art of ${word}`,

**Comment by morgante** [comment]
Oh looks like we missed inline config, thanks for the flag!
